### ISSUE TITLE
支援 RSS feed ？

### ISSUE THREAD

**Issue by linzack** [MAJA-Lin/PriceCrawler#2]
Hi Hi
請問可以支援 RSS feed 嗎？
如果可以就更實用惹 XD
謝謝！

**Comment by MAJA-Lin** [comment]
目前還不支援呢,  等我解決三民的資料問題之後看看怎麼補上XD

**Comment by MAJA-Lin** [comment]
Hello,
Rss Feed的功能完成了, 連結如下
https://safe-shelf-6136.herokuapp.com/book/discount/week/rss.xml
如果還有什麼意見的話, 歡迎提供!

**Comment by linzack** [comment]
Hi~~
剛剛試了一下 feed 看來是空的也 XD
啊 是不是要等到update的時間才會有東西  哈哈
我已經加到feedly惹  坐等更新 wwwww
謝謝啦~~很酷的feature!

**Comment by MAJA-Lin** [comment]
是空的嗎0.0
我現在看是有東西耶
不過目前只有保留有更新東西的時間，上一次更新跟上上次更新之類的不會保存下來
還是你可以截圖給我看呢?

**Comment by linzack** [comment]
恩阿
我原本以爲會有折扣書的內容 XD
不過照你的說法 好像是 網站上資料更新的時間 是嗎？哈哈
這個是我看到的截圖~~
![rss1](https://cloud.githubusercontent.com/assets/8398628/18416394/12579b9a-7846-11e6-88bc-eef0a66f0f9f.PNG)
像這個是 [yahoo新聞的 rss](https://tw.news.yahoo.com/rss/)
比如在 item 的 description 會有新聞的內容之類的~~

**Comment by MAJA-Lin** [comment]
喔喔我懂你意思了, 那我之後再作修正
